# Generated by Django 5.0.4 on 2024-05-04 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('contract_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Активно'), ('reserved', 'Бронь'), ('sold', 'Продано'), ('instalment', 'Рассрочка'), ('barter', 'Бартер')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('number_of_deals', models.IntegerField()),
                ('temporary_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('square_meters', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Активно'), ('reserved', 'Бронь'), ('sold', 'Продано'), ('instalment', 'Рассрочка'), ('barter', 'Бартер')], default='active', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
                ('object_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.objectname')),
            ],
        ),
    ]
