# Generated by Django 5.0.4 on 2024-05-04 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.client'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='В сомах', max_digits=10),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='square_meters',
            field=models.DecimalField(decimal_places=2, help_text='Метр в квадрате', max_digits=10),
        ),
    ]
